### PR TITLE
Added react component example

### PR DESCRIPTION
**Pull request by callum-gander**
Added a react component example in the "use_as_react_component" directory and updated the main README to include this

### CODE REVIEW

**Comment by kovacsv** [comment]
I've tried it on Windows. After `npm install` and `npm run dev` I've opened localhost:3000, but the page doesn't load. I get this in the console:
```
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
TypeError: Cannot read properties of null (reading 'useContext')
    at Object.useContext (C:\Users\Viktor\GitRepos\Online3DViewerExamplesCallum\use_as_react_component\node_modules\react\cjs\react.development.js:1618:21)
    at Html (webpack-internal:///./node_modules/next/dist/pages/_document.js:678:104)
    at renderWithHooks (c:\Users\Viktor\GitRepos\Online3DViewerExamplesCallum\use_as_react_component\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5658:16)
    at renderIndeterminateComponent (c:\Users\Viktor\GitRepos\Online3DViewerExamplesCallum\use_as_react_component\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5731:15)
    at renderElement (c:\Users\Viktor\GitRepos\Online3DViewerExamplesCallum\use_as_react_component\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (c:\Users\Viktor\GitRepos\Online3DViewerExamplesCallum\use_as_react_component\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (c:\Users\Viktor\GitRepos\Online3DViewerExamplesCallum\use_as_react_component\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at finishClassComponent (c:\Users\Viktor\GitRepos\Online3DViewerExamplesCallum\use_as_react_component\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5688:3)
    at renderClassComponent (c:\Users\Viktor\GitRepos\Online3DViewerExamplesCallum\use_as_react_component\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5696:3)
    at renderElement (c:\Users\Viktor\GitRepos\Online3DViewerExamplesCallum\use_as_react_component\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5943:7)
TypeError: Cannot read properties of null (reading 'useContext')
    at Object.useContext (C:\Users\Viktor\GitRepos\Online3DViewerExamplesCallum\use_as_react_component\node_modules\react\cjs\react.development.js:1618:21)
    at Html (webpack-internal:///./node_modules/next/dist/pages/_document.js:678:104)
    at renderWithHooks (c:\Users\Viktor\GitRepos\Online3DViewerExamplesCallum\use_as_react_component\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5658:16)
    at renderIndeterminateComponent (c:\Users\Viktor\GitRepos\Online3DViewerExamplesCallum\use_as_react_component\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5731:15)
    at renderElement (c:\Users\Viktor\GitRepos\Online3DViewerExamplesCallum\use_as_react_component\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (c:\Users\Viktor\GitRepos\Online3DViewerExamplesCallum\use_as_react_component\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (c:\Users\Viktor\GitRepos\Online3DViewerExamplesCallum\use_as_react_component\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at finishClassComponent (c:\Users\Viktor\GitRepos\Online3DViewerExamplesCallum\use_as_react_component\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5688:3)
    at renderClassComponent (c:\Users\Viktor\GitRepos\Online3DViewerExamplesCallum\use_as_react_component\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5696:3)
    at renderElement (c:\Users\Viktor\GitRepos\Online3DViewerExamplesCallum\use_as_react_component\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5943:7)
```

And on running there is also a warning, maybe related:
```
warn  - Invalid casing detected for project dir, received c:\Users\Viktor\GitRepos\Online3DViewerExamplesCallum\use_as_react_component actual path C:\Users\Viktor\GitRepos\Online3DViewerExamplesCallum\use_as_react_component, see more info here https://nextjs.org/docs/messages/invalid-project-dir-casing
```

It's the first "C" if you are wondering. 🙂

**Comment by callum-gander** [comment]
This is really strange. I've just tested on Windows 11, both with and without WSL2, as well as on MacOS and Linux (Manjaro), as well as with both Firefox and Chrome, and it's working on all of them. 

Screenshot 2022-11-05 154533

It could be related to that warning, I can't say I've ever seen that warning before as I never use Windows without WSL2 for development. After some google, I found this https://github.com/vercel/next.js/discussions/33299 which shows that this is an ongoing issue with running the latest versions of Nextjs on Windows without WSL2. Could you possibly try out some of the solutions suggested there or, if you have WSL installed locally, test it using WSL. I don't think this is an issue with the code itself and more an issue with Next and windows

**Comment by kovacsv** [comment]
Probably it's just on my machine, I'll check if I'll have some time.

**Comment by kovacsv** [comment]
Thank you for this detailed documentation, it will be a really big help for everyone using Online 3D Viewer with React.

**Comment by kovacsv** [comment]
By running `npm run dev` from powershell it works perfectly!

**Pull request merged**
